Adding show_help function

diff --git a/shell_scripts/colnum b/shell_scripts/colnum
--- a/shell_scripts/colnum
+++ b/shell_scripts/colnum
@@ -1,5 +1,24 @@
 #!/bin/zsh
 
+show_help() {
+echo "
+
+        Usage: Environment DBPassword [-V Version] [-R Revision] [-S Schema] [-P] [-F] [-U Username]
+
+        -V Version      Version to deploy.
+        -R Revision     Revision number (0 means the latest revision).
+        -S Schema       Schema in the DB to deploy.
+        -F              Full deploy
+        -U              Username. This User who run the deploy.
+
+        For Example: ./deploy server1 123456 -V v1.0 -R 12345 -S schema1 -P -F -U User1
+
+        -H              Help
+
+"
+}
+
+
 sep="^"
 ex=0
 
@@ -14,7 +33,9 @@ while getopts ":es:h" opt; do
       show_help
       exit 0;;
     \?)
-      echo "Invalid option: -$OPTARG. Use -h flag for help." >&2;;
+      echo "Invalid option: -$OPTARG. Use -h flag for help." >&2
+      show_help
+      exit 2;;
   esac
 done
 
